package dev.librecybernetics.parser.toml

import cats.ApplicativeError
import cats.data.Validated
import cats.parse.Parser
import cats.implicits.*
import org.openjdk.jmh.annotations.*

import dev.librecybernetics.parser.readTOML
import dev.librecybernetics.parser.toml.Simple.Webserver
import dev.librecybernetics.typeclasses.Decoder
import dev.librecybernetics.types.TOML
import dev.librecybernetics.types.toml.{*, given}

@State(Scope.Benchmark)
object Simple:
  case class Author(name: String, email: String)

  given Decoder[Author, TOML.Map] with
    def decode[F[+_]: [M[_]] =>> ApplicativeError[M, Set[Decoder.Error]]](toml: TOML.Map): F[Author] =
      ApplicativeError.apply.fromValidated(
        (
          toml.decodeField[String, TOML.String]("name"),
          toml.decodeField[String, TOML.String]("email")
        ).mapN(Author.apply)
      )

  case class Project(name: String, version: String)

  given Decoder[Project, TOML.Map] with
    def decode[F[+_]: [M[_]] =>> ApplicativeError[M, Set[Decoder.Error]]](toml: TOML.Map): F[Project] =
      ApplicativeError.apply.fromValidated(
        (
          toml.decodeField[String, TOML.String]("name"),
          toml.decodeField[String, TOML.String]("version")
        ).mapN(Project.apply)
      )

  case class Dependency(name: String, version: String)

  given Decoder[Dependency, TOML.Map] with
    def decode[F[+_]: [M[_]] =>> ApplicativeError[M, Set[Decoder.Error]]](toml: TOML.Map): F[Dependency] =
      ApplicativeError.apply.fromValidated(
        (
          toml.decodeField[String, TOML.String]("name"),
          toml.decodeField[String, TOML.String]("version")
        ).mapN(Dependency.apply)
      )

  case class Database(
      `type`: String,
      host: String,
      port: Int,
      username: String,
      password: String
  )

  given Decoder[Database, TOML.Map] with
    def decode[F[+_]: [M[_]] =>> ApplicativeError[M, Set[Decoder.Error]]](toml: TOML.Map): F[Database] =
      ApplicativeError.apply.fromValidated(
        (
          toml.decodeField[String, TOML.String]("type"),
          toml.decodeField[String, TOML.String]("host"),
          toml.decodeField[Int, TOML.Integer]("port"),
          toml.decodeField[String, TOML.String]("username"),
          toml.decodeField[String, TOML.String]("password")
        ).mapN(Database.apply)
      )

  case class TLS(enable: Boolean, certificate: String, private_key: String)

  given Decoder[TLS, TOML.Map] with
    def decode[F[+_]: [M[_]] =>> ApplicativeError[M, Set[Decoder.Error]]](toml: TOML.Map): F[TLS] =
      ApplicativeError.apply.fromValidated(
        (
          toml.decodeField[Boolean, TOML.Boolean]("enable"),
          toml.decodeField[String, TOML.String]("certificate"),
          toml.decodeField[String, TOML.String]("private_key")
        ).mapN(TLS.apply)
      )

  case class Webserver(
      address: String,
      port: Int,
      tls: TLS
  )

  given Decoder[Webserver, TOML.Map] with
    def decode[F[+_]: [M[_]] =>> ApplicativeError[M, Set[Decoder.Error]]](toml: TOML.Map): F[Webserver] =
      ApplicativeError.apply.fromValidated(
        (
          toml.decodeField[String, TOML.String]("address"),
          toml.decodeField[Int, TOML.Integer]("port"),
          toml.decodeField[TLS, TOML.Map]("tls")
        ).mapN(Webserver.apply)
      )

  case class Endpoint(
      route: String,
      method: String,
      response_code: Int
  )

  given Decoder[Endpoint, TOML.Map] with
    def decode[F[+_]: [M[_]] =>> ApplicativeError[M, Set[Decoder.Error]]](toml: TOML.Map): F[Endpoint] =
      ApplicativeError.apply.fromValidated(
        (
          toml.decodeField[String, TOML.String]("route"),
          toml.decodeField[String, TOML.String]("method"),
          toml.decodeField[Int, TOML.Integer]("response_code")
        ).mapN(Endpoint.apply)
      )

  case class WholeTOML(
      author: Author,
      webserver: Webserver
  )

  given wholeTOMLDecoder: Decoder[WholeTOML, TOML.Map] with
    def decode[F[+_]: [M[_]] =>> ApplicativeError[M, Set[Decoder.Error]]](toml: TOML.Map): F[WholeTOML] =
      ApplicativeError.apply.fromValidated(
        (
          toml.decodeField[Author, TOML.Map]("author"),
          toml.decodeField[Webserver, TOML.Map]("webserver")
        ).mapN(WholeTOML.apply)
      )

  // Generated by ChatGPT (GPT-4)
  val sample: String =
    """[author]
      |name = "Jane Doe"
      |email = "jane.doe@example.com"
      |
      |[project]
      |name = "TOMLv1.0.0 Parser"
      |version = "1.0.0"
      |
      |[[dependencies]]
      |name = "library1"
      |version = "2.4.1"
      |
      |[[dependencies]]
      |name = "library2"
      |version = "3.1.0"
      |
      |[database]
      |type = "postgres"
      |host = "localhost"
      |port = 5432
      |username = "dbuser"
      |password = "dbpassword"
      |
      |[webserver]
      |address = "0.0.0.0"
      |port = 8080
      |
      |[webserver.tls]
      |enable = true
      |certificate = "/path/to/cert.pem"
      |private_key = "/path/to/key.pem"
      |
      |[[endpoints]]
      |route = "/api/v1/users"
      |method = "GET"
      |response_code = 200
      |
      |[[endpoints]]
      |route = "/api/v1/users"
      |method = "POST"
      |response_code = 201
      |
      |[[endpoints]]
      |route = "/api/v1/users/:id"
      |method = "PUT"
      |response_code = 200
      |
      |[[endpoints]]
      |route = "/api/v1/users/:id"
      |method = "DELETE"
      |response_code = 204
      |
      |[logging]
      |level = "info"
      |path = "/var/log/toml_parser.log"
      |
      |[[users]]
      |id = 1
      |name = "Alice"
      |email = "alice@example.com"
      |
      |[[users]]
      |id = 2
      |name = "Bob"
      |email = "bob@example.com"
      |
      |[[users]]
      |id = 3
      |name = "Charlie"
      |email = "charlie@example.com"
    """.stripMargin

class Simple:
  @Benchmark
  def main(): Unit =
    val Right(toml)      = readTOML[Either[Parser.Error, _]](Simple.sample): @unchecked
    val Right(structured) = Simple.wholeTOMLDecoder.decode(toml): @unchecked
    assert(structured.author.name == "Jane Doe")
    assert(structured.author.email == "jane.doe@example.com")
