package dev.librecybernetics.parser.toml

import cats.ApplicativeError
import cats.data.Validated
import cats.parse.Parser
import cats.implicits.*
import org.openjdk.jmh.annotations.*

import dev.librecybernetics.parser.readTOML
import dev.librecybernetics.parser.toml.Simple.Webserver
import dev.librecybernetics.typeclasses.Decoder
import dev.librecybernetics.types.TOML
import dev.librecybernetics.types.toml.{*, given}

@State(Scope.Benchmark)
object Simple:
  case class Author(name: String, email: String)
  given Decoder[Author, TOML] = TOMLDecoder.derived

  case class Project(name: String, version: String)
  given Decoder[Project, TOML] = TOMLDecoder.derived

  case class Dependency(name: String, version: String)
  given Decoder[Dependency, TOML] = TOMLDecoder.derived

  case class Database(
      `type`: String,
      host: String,
      port: Int,
      username: String,
      password: String
  )
  given Decoder[Database, TOML] = TOMLDecoder.derived

  case class TLS(enable: Boolean, certificate: String, private_key: String)
  given Decoder[TLS, TOML] = TOMLDecoder.derived

  case class Webserver(
      address: String,
      port: Int,
      tls: TLS
  )
  given Decoder[Webserver, TOML] = TOMLDecoder.derived

  case class Endpoint(
      route: String,
      method: String,
      response_code: Int
  )
  given Decoder[Endpoint, TOML] = TOMLDecoder.derived

  case class WholeTOML(
      author: Author,
      webserver: Webserver
  )
  given wholeTOMLDecoder: Decoder[WholeTOML, TOML] = TOMLDecoder.derived

  // Generated by ChatGPT (GPT-4)
  val sample: String =
    """[author]
      |name = "Jane Doe"
      |email = "jane.doe@example.com"
      |
      |[project]
      |name = "TOMLv1.0.0 Parser"
      |version = "1.0.0"
      |
      |[[dependencies]]
      |name = "library1"
      |version = "2.4.1"
      |
      |[[dependencies]]
      |name = "library2"
      |version = "3.1.0"
      |
      |[database]
      |type = "postgres"
      |host = "localhost"
      |port = 5432
      |username = "dbuser"
      |password = "dbpassword"
      |
      |[webserver]
      |address = "0.0.0.0"
      |port = 8080
      |
      |[webserver.tls]
      |enable = true
      |certificate = "/path/to/cert.pem"
      |private_key = "/path/to/key.pem"
      |
      |[[endpoints]]
      |route = "/api/v1/users"
      |method = "GET"
      |response_code = 200
      |
      |[[endpoints]]
      |route = "/api/v1/users"
      |method = "POST"
      |response_code = 201
      |
      |[[endpoints]]
      |route = "/api/v1/users/:id"
      |method = "PUT"
      |response_code = 200
      |
      |[[endpoints]]
      |route = "/api/v1/users/:id"
      |method = "DELETE"
      |response_code = 204
      |
      |[logging]
      |level = "info"
      |path = "/var/log/toml_parser.log"
      |
      |[[users]]
      |id = 1
      |name = "Alice"
      |email = "alice@example.com"
      |
      |[[users]]
      |id = 2
      |name = "Bob"
      |email = "bob@example.com"
      |
      |[[users]]
      |id = 3
      |name = "Charlie"
      |email = "charlie@example.com"
    """.stripMargin

class Simple:
  @Benchmark
  def main(): Unit =
    val Right(toml)       = readTOML[Either[Parser.Error, _]](Simple.sample): @unchecked
    val Right(structured) = Simple.wholeTOMLDecoder.decode(toml): @unchecked
    assert(structured.author.name == "Jane Doe")
    assert(structured.author.email == "jane.doe@example.com")
    assert(structured.webserver.address == "0.0.0.0")
    assert(structured.webserver.port == 8080)
    assert(structured.webserver.tls.enable)
    assert(structured.webserver.tls.certificate == "/path/to/cert.pem")
