name: Kotlin Multiformats

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Test with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: test
        gradle-version: current
        build-root-directory: kotlin/multiformats
    - name: Code Climate
      uses: paambaati/codeclimate-action@v3.0.0
      env:
        CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
        JACOCO_SOURCE_PATH: ${{github.workspace}}/kotlin/multiformats/lib/src/main/kotlin
      with:
        coverageLocations: ${{github.workspace}}/kotlin/multiformats/lib/build/reports/jacoco/test/jacocoTestReport.xml:jacoco
